/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class BatteryStatus extends Object {
	public BatteryStatus() {
	}

	private StateOfCharge stateOfCharge;

	private ChargeLevel chargeLevel;

	private StateOfHealth stateOfHealth;

	private Double voltage;

	public StateOfCharge getStateOfCharge() {
		
		return this.stateOfCharge;
	}
	
	public ChargeLevel getChargeLevel() {
		
		return this.chargeLevel;
	}
	
	public StateOfHealth getStateOfHealth() {
		
		return this.stateOfHealth;
	}
	
	public Double getVoltage() {
		
		return this.voltage;
	}
	
	public void setStateOfCharge(StateOfCharge stateOfCharge) {
		
		this.stateOfCharge = stateOfCharge;
	}

	public void setChargeLevel(ChargeLevel chargeLevel) {
		
		this.chargeLevel = chargeLevel;
	}

	public void setStateOfHealth(StateOfHealth stateOfHealth) {
		
		this.stateOfHealth = stateOfHealth;
	}

	public void setVoltage(Double voltage) {
		
		this.voltage = voltage;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		BatteryStatus comparator = (BatteryStatus)anObject;

		if ((this.getStateOfCharge() != comparator.getStateOfCharge()) && ((this.getStateOfCharge() == null) || (! this.getStateOfCharge().equals(comparator.getStateOfCharge())))) return false;
		if ((this.getChargeLevel() != comparator.getChargeLevel()) && ((this.getChargeLevel() == null) || (! this.getChargeLevel().equals(comparator.getChargeLevel())))) return false;
		if ((this.getStateOfHealth() != comparator.getStateOfHealth()) && ((this.getStateOfHealth() == null) || (! this.getStateOfHealth().equals(comparator.getStateOfHealth())))) return false;
		if ((this.getVoltage() != comparator.getVoltage()) && ((this.getVoltage() == null) || (! this.getVoltage().equals(comparator.getVoltage())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 727;

		hash = 1069 * hash + (null == this.getStateOfCharge() ? 0 : this.getStateOfCharge().hashCode());
		hash = 1291 * hash + (null == this.getChargeLevel() ? 0 : this.getChargeLevel().hashCode());
		hash = 6301 * hash + (null == this.getStateOfHealth() ? 0 : this.getStateOfHealth().hashCode());
		hash = 3797 * hash + (null == this.getVoltage() ? 0 : this.getVoltage().hashCode());
		return hash;
	}

}
