/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class BehaviourBasicKeyFactor extends Object {
	public BehaviourBasicKeyFactor() {
	}

	private Double durationOverThreshold;

	private Double dfbSpeed;

	public Double getDurationOverThreshold() {
		
		return this.durationOverThreshold;
	}
	
	public Double getDfbSpeed() {
		
		return this.dfbSpeed;
	}
	
	public void setDurationOverThreshold(Double durationOverThreshold) {
		
		this.durationOverThreshold = durationOverThreshold;
	}

	public void setDfbSpeed(Double dfbSpeed) {
		
		this.dfbSpeed = dfbSpeed;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		BehaviourBasicKeyFactor comparator = (BehaviourBasicKeyFactor)anObject;

		if ((this.getDurationOverThreshold() != comparator.getDurationOverThreshold()) && ((this.getDurationOverThreshold() == null) || (! this.getDurationOverThreshold().equals(comparator.getDurationOverThreshold())))) return false;
		if ((this.getDfbSpeed() != comparator.getDfbSpeed()) && ((this.getDfbSpeed() == null) || (! this.getDfbSpeed().equals(comparator.getDfbSpeed())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 991;

		hash = 1279 * hash + (null == this.getDurationOverThreshold() ? 0 : this.getDurationOverThreshold().hashCode());
		hash = 6733 * hash + (null == this.getDfbSpeed() ? 0 : this.getDfbSpeed().hashCode());
		return hash;
	}

}
