/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Customer extends Object {
	public Customer() {
	}

	private List<Passengers> passengers;

	private Long passengerCount;

	private String passengerStatus;

	public List<Passengers> getPassengers() {
		
		return this.passengers;
	}
	
	public Long getPassengerCount() {
		
		return this.passengerCount;
	}
	
	public String getPassengerStatus() {
		
		return this.passengerStatus;
	}
	
	public void setPassengers(List<Passengers> passengers) {
		
		this.passengers = passengers;
	}

	public void setPassengerCount(Long passengerCount) {
		
		this.passengerCount = passengerCount;
	}

	public void setPassengerStatus(String passengerStatus) {
		
		this.passengerStatus = passengerStatus;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Customer comparator = (Customer)anObject;

		if ((this.getPassengers() != comparator.getPassengers()) && ((this.getPassengers() == null) || (! this.getPassengers().equals(comparator.getPassengers())))) return false;
		if ((this.getPassengerCount() != comparator.getPassengerCount()) && ((this.getPassengerCount() == null) || (! this.getPassengerCount().equals(comparator.getPassengerCount())))) return false;
		if ((this.getPassengerStatus() != comparator.getPassengerStatus()) && ((this.getPassengerStatus() == null) || (! this.getPassengerStatus().equals(comparator.getPassengerStatus())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 4327;

		hash = 4637 * hash + (null == this.getPassengers() ? 0 : this.getPassengers().hashCode());
		hash = 7219 * hash + (null == this.getPassengerCount() ? 0 : this.getPassengerCount().hashCode());
		hash = 7561 * hash + (null == this.getPassengerStatus() ? 0 : this.getPassengerStatus().hashCode());
		return hash;
	}

}
