/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class DiagnosticTroubleCode extends Object {
	public DiagnosticTroubleCode() {
	}

	private String dtc;

	private String dtcAdvice;

	private String dtcDesc;

	private TimeStamp firstFail;

	private TimeStamp lastFail;

	private DtcStatus status;

	private Long odometer;

	private OdoStatus odoStatus;

	private Double failureBatteryVoltage;

	private Double failureVehicleSpeed;

	private Position position;

	public String getDtc() {
		
		return this.dtc;
	}
	
	public String getDtcAdvice() {
		
		return this.dtcAdvice;
	}
	
	public String getDtcDesc() {
		
		return this.dtcDesc;
	}
	
	public TimeStamp getFirstFail() {
		
		return this.firstFail;
	}
	
	public TimeStamp getLastFail() {
		
		return this.lastFail;
	}
	
	public DtcStatus getStatus() {
		
		return this.status;
	}
	
	public Long getOdometer() {
		
		return this.odometer;
	}
	
	public OdoStatus getOdoStatus() {
		
		return this.odoStatus;
	}
	
	public Double getFailureBatteryVoltage() {
		
		return this.failureBatteryVoltage;
	}
	
	public Double getFailureVehicleSpeed() {
		
		return this.failureVehicleSpeed;
	}
	
	public Position getPosition() {
		
		return this.position;
	}
	
	public void setDtc(String dtc) {
		
		this.dtc = dtc;
	}

	public void setDtcAdvice(String dtcAdvice) {
		
		this.dtcAdvice = dtcAdvice;
	}

	public void setDtcDesc(String dtcDesc) {
		
		this.dtcDesc = dtcDesc;
	}

	public void setFirstFail(TimeStamp firstFail) {
		
		this.firstFail = firstFail;
	}

	public void setLastFail(TimeStamp lastFail) {
		
		this.lastFail = lastFail;
	}

	public void setStatus(DtcStatus status) {
		
		this.status = status;
	}

	public void setOdometer(Long odometer) {
		
		this.odometer = odometer;
	}

	public void setOdoStatus(OdoStatus odoStatus) {
		
		this.odoStatus = odoStatus;
	}

	public void setFailureBatteryVoltage(Double failureBatteryVoltage) {
		
		this.failureBatteryVoltage = failureBatteryVoltage;
	}

	public void setFailureVehicleSpeed(Double failureVehicleSpeed) {
		
		this.failureVehicleSpeed = failureVehicleSpeed;
	}

	public void setPosition(Position position) {
		
		this.position = position;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		DiagnosticTroubleCode comparator = (DiagnosticTroubleCode)anObject;

		if ((this.getDtc() != comparator.getDtc()) && ((this.getDtc() == null) || (! this.getDtc().equals(comparator.getDtc())))) return false;
		if ((this.getDtcAdvice() != comparator.getDtcAdvice()) && ((this.getDtcAdvice() == null) || (! this.getDtcAdvice().equals(comparator.getDtcAdvice())))) return false;
		if ((this.getDtcDesc() != comparator.getDtcDesc()) && ((this.getDtcDesc() == null) || (! this.getDtcDesc().equals(comparator.getDtcDesc())))) return false;
		if ((this.getFirstFail() != comparator.getFirstFail()) && ((this.getFirstFail() == null) || (! this.getFirstFail().equals(comparator.getFirstFail())))) return false;
		if ((this.getLastFail() != comparator.getLastFail()) && ((this.getLastFail() == null) || (! this.getLastFail().equals(comparator.getLastFail())))) return false;
		if ((this.getStatus() != comparator.getStatus()) && ((this.getStatus() == null) || (! this.getStatus().equals(comparator.getStatus())))) return false;
		if ((this.getOdometer() != comparator.getOdometer()) && ((this.getOdometer() == null) || (! this.getOdometer().equals(comparator.getOdometer())))) return false;
		if ((this.getOdoStatus() != comparator.getOdoStatus()) && ((this.getOdoStatus() == null) || (! this.getOdoStatus().equals(comparator.getOdoStatus())))) return false;
		if ((this.getFailureBatteryVoltage() != comparator.getFailureBatteryVoltage()) && ((this.getFailureBatteryVoltage() == null) || (! this.getFailureBatteryVoltage().equals(comparator.getFailureBatteryVoltage())))) return false;
		if ((this.getFailureVehicleSpeed() != comparator.getFailureVehicleSpeed()) && ((this.getFailureVehicleSpeed() == null) || (! this.getFailureVehicleSpeed().equals(comparator.getFailureVehicleSpeed())))) return false;
		if ((this.getPosition() != comparator.getPosition()) && ((this.getPosition() == null) || (! this.getPosition().equals(comparator.getPosition())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 3391;

		hash = 5591 * hash + (null == this.getDtc() ? 0 : this.getDtc().hashCode());
		hash = 7541 * hash + (null == this.getDtcAdvice() ? 0 : this.getDtcAdvice().hashCode());
		hash = 4969 * hash + (null == this.getDtcDesc() ? 0 : this.getDtcDesc().hashCode());
		hash = 1327 * hash + (null == this.getFirstFail() ? 0 : this.getFirstFail().hashCode());
		hash = 2417 * hash + (null == this.getLastFail() ? 0 : this.getLastFail().hashCode());
		hash = 3391 * hash + (null == this.getStatus() ? 0 : this.getStatus().hashCode());
		hash = 7411 * hash + (null == this.getOdometer() ? 0 : this.getOdometer().hashCode());
		hash = 547 * hash + (null == this.getOdoStatus() ? 0 : this.getOdoStatus().hashCode());
		hash = 431 * hash + (null == this.getFailureBatteryVoltage() ? 0 : this.getFailureBatteryVoltage().hashCode());
		hash = 3967 * hash + (null == this.getFailureVehicleSpeed() ? 0 : this.getFailureVehicleSpeed().hashCode());
		hash = 7649 * hash + (null == this.getPosition() ? 0 : this.getPosition().hashCode());
		return hash;
	}

}
