/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Diagnostics extends Object {
	public Diagnostics() {
	}

	private ECUDiagnostic ecuDiagnositcs;

	private TimeStamp timeStamp;

	public ECUDiagnostic getEcuDiagnositcs() {
		
		return this.ecuDiagnositcs;
	}
	
	public TimeStamp getTimeStamp() {
		
		return this.timeStamp;
	}
	
	public void setEcuDiagnositcs(ECUDiagnostic ecuDiagnositcs) {
		
		this.ecuDiagnositcs = ecuDiagnositcs;
	}

	public void setTimeStamp(TimeStamp timeStamp) {
		
		this.timeStamp = timeStamp;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Diagnostics comparator = (Diagnostics)anObject;

		if ((this.getEcuDiagnositcs() != comparator.getEcuDiagnositcs()) && ((this.getEcuDiagnositcs() == null) || (! this.getEcuDiagnositcs().equals(comparator.getEcuDiagnositcs())))) return false;
		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 1201;

		hash = 59 * hash + (null == this.getEcuDiagnositcs() ? 0 : this.getEcuDiagnositcs().hashCode());
		hash = 1109 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		return hash;
	}

}
