/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class DrivingBehavior extends Object {
	public DrivingBehavior() {
	}

	private Behaviours behaviours;

	private TimeStamp timeStamp;

	private Boolean brakePedalDepressed;

	private Double engineSpeed;

	private TransimissionGearPostion transimissionGearPostion;

	private CruiseControlStatus cruiseControlStatus;

	public Behaviours getBehaviours() {
		
		return this.behaviours;
	}
	
	public TimeStamp getTimeStamp() {
		
		return this.timeStamp;
	}
	
	public Boolean getBrakePedalDepressed() {
		
		return this.brakePedalDepressed;
	}
	
	public Double getEngineSpeed() {
		
		return this.engineSpeed;
	}
	
	public TransimissionGearPostion getTransimissionGearPostion() {
		
		return this.transimissionGearPostion;
	}
	
	public CruiseControlStatus getCruiseControlStatus() {
		
		return this.cruiseControlStatus;
	}
	
	public void setBehaviours(Behaviours behaviours) {
		
		this.behaviours = behaviours;
	}

	public void setTimeStamp(TimeStamp timeStamp) {
		
		this.timeStamp = timeStamp;
	}

	public void setBrakePedalDepressed(Boolean brakePedalDepressed) {
		
		this.brakePedalDepressed = brakePedalDepressed;
	}

	public void setEngineSpeed(Double engineSpeed) {
		
		this.engineSpeed = engineSpeed;
	}

	public void setTransimissionGearPostion(TransimissionGearPostion transimissionGearPostion) {
		
		this.transimissionGearPostion = transimissionGearPostion;
	}

	public void setCruiseControlStatus(CruiseControlStatus cruiseControlStatus) {
		
		this.cruiseControlStatus = cruiseControlStatus;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		DrivingBehavior comparator = (DrivingBehavior)anObject;

		if ((this.getBehaviours() != comparator.getBehaviours()) && ((this.getBehaviours() == null) || (! this.getBehaviours().equals(comparator.getBehaviours())))) return false;
		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		if ((this.getBrakePedalDepressed() != comparator.getBrakePedalDepressed()) && ((this.getBrakePedalDepressed() == null) || (! this.getBrakePedalDepressed().equals(comparator.getBrakePedalDepressed())))) return false;
		if ((this.getEngineSpeed() != comparator.getEngineSpeed()) && ((this.getEngineSpeed() == null) || (! this.getEngineSpeed().equals(comparator.getEngineSpeed())))) return false;
		if ((this.getTransimissionGearPostion() != comparator.getTransimissionGearPostion()) && ((this.getTransimissionGearPostion() == null) || (! this.getTransimissionGearPostion().equals(comparator.getTransimissionGearPostion())))) return false;
		if ((this.getCruiseControlStatus() != comparator.getCruiseControlStatus()) && ((this.getCruiseControlStatus() == null) || (! this.getCruiseControlStatus().equals(comparator.getCruiseControlStatus())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 131;

		hash = 1381 * hash + (null == this.getBehaviours() ? 0 : this.getBehaviours().hashCode());
		hash = 5171 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		hash = 683 * hash + (null == this.getBrakePedalDepressed() ? 0 : this.getBrakePedalDepressed().hashCode());
		hash = 5351 * hash + (null == this.getEngineSpeed() ? 0 : this.getEngineSpeed().hashCode());
		hash = 7723 * hash + (null == this.getTransimissionGearPostion() ? 0 : this.getTransimissionGearPostion().hashCode());
		hash = 7129 * hash + (null == this.getCruiseControlStatus() ? 0 : this.getCruiseControlStatus().hashCode());
		return hash;
	}

}
