/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class DrivingSafety extends Object {
	public DrivingSafety() {
	}

	private SrsStatus srsStatus;

	private DoorStatus doorOpenStatusDriver;

	private DoorStatus doorOpenStatusPassenger;

	private DoorStatus doorOpenStatusDriverRear;

	private DoorStatus doorOpenStatusPassengerRear;

	private DoorLockedStatus doorLockStatusDriver;

	private DoorLockedStatus doorLockStatusPassenger;

	private DoorLockedStatus doorLockStatusDriverRear;

	private DoorLockedStatus doorLockStatusPassengerRear;

	private Boolean seatBeltStatusDriver;

	private Boolean seatBeltStatusPassenger;

	private Boolean seatBeltStatusDriverRear;

	private Boolean seatBeltStatusPassengerRear;

	private HandBrakeStatus handBrakeStatus;

	private ElectricParkBrakeStatus electricParkBrakeStatus;

	private TimeStamp timeStamp;

	private TrunkStatus trunkOpenStatus;

	private EngineHoodStatus engineHoodOpenStatus;

	private CentralLockingStatus centralLockingStatus;

	public SrsStatus getSrsStatus() {
		
		return this.srsStatus;
	}
	
	public DoorStatus getDoorOpenStatusDriver() {
		
		return this.doorOpenStatusDriver;
	}
	
	public DoorStatus getDoorOpenStatusPassenger() {
		
		return this.doorOpenStatusPassenger;
	}
	
	public DoorStatus getDoorOpenStatusDriverRear() {
		
		return this.doorOpenStatusDriverRear;
	}
	
	public DoorStatus getDoorOpenStatusPassengerRear() {
		
		return this.doorOpenStatusPassengerRear;
	}
	
	public DoorLockedStatus getDoorLockStatusDriver() {
		
		return this.doorLockStatusDriver;
	}
	
	public DoorLockedStatus getDoorLockStatusPassenger() {
		
		return this.doorLockStatusPassenger;
	}
	
	public DoorLockedStatus getDoorLockStatusDriverRear() {
		
		return this.doorLockStatusDriverRear;
	}
	
	public DoorLockedStatus getDoorLockStatusPassengerRear() {
		
		return this.doorLockStatusPassengerRear;
	}
	
	public Boolean getSeatBeltStatusDriver() {
		
		return this.seatBeltStatusDriver;
	}
	
	public Boolean getSeatBeltStatusPassenger() {
		
		return this.seatBeltStatusPassenger;
	}
	
	public Boolean getSeatBeltStatusDriverRear() {
		
		return this.seatBeltStatusDriverRear;
	}
	
	public Boolean getSeatBeltStatusPassengerRear() {
		
		return this.seatBeltStatusPassengerRear;
	}
	
	public HandBrakeStatus getHandBrakeStatus() {
		
		return this.handBrakeStatus;
	}
	
	public ElectricParkBrakeStatus getElectricParkBrakeStatus() {
		
		return this.electricParkBrakeStatus;
	}
	
	public TimeStamp getTimeStamp() {
		
		return this.timeStamp;
	}
	
	public TrunkStatus getTrunkOpenStatus() {
		
		return this.trunkOpenStatus;
	}
	
	public EngineHoodStatus getEngineHoodOpenStatus() {
		
		return this.engineHoodOpenStatus;
	}
	
	public CentralLockingStatus getCentralLockingStatus() {
		
		return this.centralLockingStatus;
	}
	
	public void setSrsStatus(SrsStatus srsStatus) {
		
		this.srsStatus = srsStatus;
	}

	public void setDoorOpenStatusDriver(DoorStatus doorOpenStatusDriver) {
		
		this.doorOpenStatusDriver = doorOpenStatusDriver;
	}

	public void setDoorOpenStatusPassenger(DoorStatus doorOpenStatusPassenger) {
		
		this.doorOpenStatusPassenger = doorOpenStatusPassenger;
	}

	public void setDoorOpenStatusDriverRear(DoorStatus doorOpenStatusDriverRear) {
		
		this.doorOpenStatusDriverRear = doorOpenStatusDriverRear;
	}

	public void setDoorOpenStatusPassengerRear(DoorStatus doorOpenStatusPassengerRear) {
		
		this.doorOpenStatusPassengerRear = doorOpenStatusPassengerRear;
	}

	public void setDoorLockStatusDriver(DoorLockedStatus doorLockStatusDriver) {
		
		this.doorLockStatusDriver = doorLockStatusDriver;
	}

	public void setDoorLockStatusPassenger(DoorLockedStatus doorLockStatusPassenger) {
		
		this.doorLockStatusPassenger = doorLockStatusPassenger;
	}

	public void setDoorLockStatusDriverRear(DoorLockedStatus doorLockStatusDriverRear) {
		
		this.doorLockStatusDriverRear = doorLockStatusDriverRear;
	}

	public void setDoorLockStatusPassengerRear(DoorLockedStatus doorLockStatusPassengerRear) {
		
		this.doorLockStatusPassengerRear = doorLockStatusPassengerRear;
	}

	public void setSeatBeltStatusDriver(Boolean seatBeltStatusDriver) {
		
		this.seatBeltStatusDriver = seatBeltStatusDriver;
	}

	public void setSeatBeltStatusPassenger(Boolean seatBeltStatusPassenger) {
		
		this.seatBeltStatusPassenger = seatBeltStatusPassenger;
	}

	public void setSeatBeltStatusDriverRear(Boolean seatBeltStatusDriverRear) {
		
		this.seatBeltStatusDriverRear = seatBeltStatusDriverRear;
	}

	public void setSeatBeltStatusPassengerRear(Boolean seatBeltStatusPassengerRear) {
		
		this.seatBeltStatusPassengerRear = seatBeltStatusPassengerRear;
	}

	public void setHandBrakeStatus(HandBrakeStatus handBrakeStatus) {
		
		this.handBrakeStatus = handBrakeStatus;
	}

	public void setElectricParkBrakeStatus(ElectricParkBrakeStatus electricParkBrakeStatus) {
		
		this.electricParkBrakeStatus = electricParkBrakeStatus;
	}

	public void setTimeStamp(TimeStamp timeStamp) {
		
		this.timeStamp = timeStamp;
	}

	public void setTrunkOpenStatus(TrunkStatus trunkOpenStatus) {
		
		this.trunkOpenStatus = trunkOpenStatus;
	}

	public void setEngineHoodOpenStatus(EngineHoodStatus engineHoodOpenStatus) {
		
		this.engineHoodOpenStatus = engineHoodOpenStatus;
	}

	public void setCentralLockingStatus(CentralLockingStatus centralLockingStatus) {
		
		this.centralLockingStatus = centralLockingStatus;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		DrivingSafety comparator = (DrivingSafety)anObject;

		if ((this.getSrsStatus() != comparator.getSrsStatus()) && ((this.getSrsStatus() == null) || (! this.getSrsStatus().equals(comparator.getSrsStatus())))) return false;
		if ((this.getDoorOpenStatusDriver() != comparator.getDoorOpenStatusDriver()) && ((this.getDoorOpenStatusDriver() == null) || (! this.getDoorOpenStatusDriver().equals(comparator.getDoorOpenStatusDriver())))) return false;
		if ((this.getDoorOpenStatusPassenger() != comparator.getDoorOpenStatusPassenger()) && ((this.getDoorOpenStatusPassenger() == null) || (! this.getDoorOpenStatusPassenger().equals(comparator.getDoorOpenStatusPassenger())))) return false;
		if ((this.getDoorOpenStatusDriverRear() != comparator.getDoorOpenStatusDriverRear()) && ((this.getDoorOpenStatusDriverRear() == null) || (! this.getDoorOpenStatusDriverRear().equals(comparator.getDoorOpenStatusDriverRear())))) return false;
		if ((this.getDoorOpenStatusPassengerRear() != comparator.getDoorOpenStatusPassengerRear()) && ((this.getDoorOpenStatusPassengerRear() == null) || (! this.getDoorOpenStatusPassengerRear().equals(comparator.getDoorOpenStatusPassengerRear())))) return false;
		if ((this.getDoorLockStatusDriver() != comparator.getDoorLockStatusDriver()) && ((this.getDoorLockStatusDriver() == null) || (! this.getDoorLockStatusDriver().equals(comparator.getDoorLockStatusDriver())))) return false;
		if ((this.getDoorLockStatusPassenger() != comparator.getDoorLockStatusPassenger()) && ((this.getDoorLockStatusPassenger() == null) || (! this.getDoorLockStatusPassenger().equals(comparator.getDoorLockStatusPassenger())))) return false;
		if ((this.getDoorLockStatusDriverRear() != comparator.getDoorLockStatusDriverRear()) && ((this.getDoorLockStatusDriverRear() == null) || (! this.getDoorLockStatusDriverRear().equals(comparator.getDoorLockStatusDriverRear())))) return false;
		if ((this.getDoorLockStatusPassengerRear() != comparator.getDoorLockStatusPassengerRear()) && ((this.getDoorLockStatusPassengerRear() == null) || (! this.getDoorLockStatusPassengerRear().equals(comparator.getDoorLockStatusPassengerRear())))) return false;
		if ((this.getSeatBeltStatusDriver() != comparator.getSeatBeltStatusDriver()) && ((this.getSeatBeltStatusDriver() == null) || (! this.getSeatBeltStatusDriver().equals(comparator.getSeatBeltStatusDriver())))) return false;
		if ((this.getSeatBeltStatusPassenger() != comparator.getSeatBeltStatusPassenger()) && ((this.getSeatBeltStatusPassenger() == null) || (! this.getSeatBeltStatusPassenger().equals(comparator.getSeatBeltStatusPassenger())))) return false;
		if ((this.getSeatBeltStatusDriverRear() != comparator.getSeatBeltStatusDriverRear()) && ((this.getSeatBeltStatusDriverRear() == null) || (! this.getSeatBeltStatusDriverRear().equals(comparator.getSeatBeltStatusDriverRear())))) return false;
		if ((this.getSeatBeltStatusPassengerRear() != comparator.getSeatBeltStatusPassengerRear()) && ((this.getSeatBeltStatusPassengerRear() == null) || (! this.getSeatBeltStatusPassengerRear().equals(comparator.getSeatBeltStatusPassengerRear())))) return false;
		if ((this.getHandBrakeStatus() != comparator.getHandBrakeStatus()) && ((this.getHandBrakeStatus() == null) || (! this.getHandBrakeStatus().equals(comparator.getHandBrakeStatus())))) return false;
		if ((this.getElectricParkBrakeStatus() != comparator.getElectricParkBrakeStatus()) && ((this.getElectricParkBrakeStatus() == null) || (! this.getElectricParkBrakeStatus().equals(comparator.getElectricParkBrakeStatus())))) return false;
		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		if ((this.getTrunkOpenStatus() != comparator.getTrunkOpenStatus()) && ((this.getTrunkOpenStatus() == null) || (! this.getTrunkOpenStatus().equals(comparator.getTrunkOpenStatus())))) return false;
		if ((this.getEngineHoodOpenStatus() != comparator.getEngineHoodOpenStatus()) && ((this.getEngineHoodOpenStatus() == null) || (! this.getEngineHoodOpenStatus().equals(comparator.getEngineHoodOpenStatus())))) return false;
		if ((this.getCentralLockingStatus() != comparator.getCentralLockingStatus()) && ((this.getCentralLockingStatus() == null) || (! this.getCentralLockingStatus().equals(comparator.getCentralLockingStatus())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 3389;

		hash = 601 * hash + (null == this.getSrsStatus() ? 0 : this.getSrsStatus().hashCode());
		hash = 751 * hash + (null == this.getDoorOpenStatusDriver() ? 0 : this.getDoorOpenStatusDriver().hashCode());
		hash = 4289 * hash + (null == this.getDoorOpenStatusPassenger() ? 0 : this.getDoorOpenStatusPassenger().hashCode());
		hash = 6857 * hash + (null == this.getDoorOpenStatusDriverRear() ? 0 : this.getDoorOpenStatusDriverRear().hashCode());
		hash = 4861 * hash + (null == this.getDoorOpenStatusPassengerRear() ? 0 : this.getDoorOpenStatusPassengerRear().hashCode());
		hash = 239 * hash + (null == this.getDoorLockStatusDriver() ? 0 : this.getDoorLockStatusDriver().hashCode());
		hash = 1487 * hash + (null == this.getDoorLockStatusPassenger() ? 0 : this.getDoorLockStatusPassenger().hashCode());
		hash = 7687 * hash + (null == this.getDoorLockStatusDriverRear() ? 0 : this.getDoorLockStatusDriverRear().hashCode());
		hash = 5147 * hash + (null == this.getDoorLockStatusPassengerRear() ? 0 : this.getDoorLockStatusPassengerRear().hashCode());
		hash = 1087 * hash + (null == this.getSeatBeltStatusDriver() ? 0 : this.getSeatBeltStatusDriver().hashCode());
		hash = 3307 * hash + (null == this.getSeatBeltStatusPassenger() ? 0 : this.getSeatBeltStatusPassenger().hashCode());
		hash = 569 * hash + (null == this.getSeatBeltStatusDriverRear() ? 0 : this.getSeatBeltStatusDriverRear().hashCode());
		hash = 7309 * hash + (null == this.getSeatBeltStatusPassengerRear() ? 0 : this.getSeatBeltStatusPassengerRear().hashCode());
		hash = 1471 * hash + (null == this.getHandBrakeStatus() ? 0 : this.getHandBrakeStatus().hashCode());
		hash = 953 * hash + (null == this.getElectricParkBrakeStatus() ? 0 : this.getElectricParkBrakeStatus().hashCode());
		hash = 4133 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		hash = 3607 * hash + (null == this.getTrunkOpenStatus() ? 0 : this.getTrunkOpenStatus().hashCode());
		hash = 4787 * hash + (null == this.getEngineHoodOpenStatus() ? 0 : this.getEngineHoodOpenStatus().hashCode());
		hash = 7243 * hash + (null == this.getCentralLockingStatus() ? 0 : this.getCentralLockingStatus().hashCode());
		return hash;
	}

}
