/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Driver extends Object {
	public Driver() {
	}

	private String displayName;

	private String idCardNo;

	private String gender;

	private String driverId;

	private String driverLicenseNum;

	public String getDisplayName() {
		
		return this.displayName;
	}
	
	public String getIdCardNo() {
		
		return this.idCardNo;
	}
	
	public String getGender() {
		
		return this.gender;
	}
	
	public String getDriverId() {
		
		return this.driverId;
	}
	
	public String getDriverLicenseNum() {
		
		return this.driverLicenseNum;
	}
	
	public void setDisplayName(String displayName) {
		
		this.displayName = displayName;
	}

	public void setIdCardNo(String idCardNo) {
		
		this.idCardNo = idCardNo;
	}

	public void setGender(String gender) {
		
		this.gender = gender;
	}

	public void setDriverId(String driverId) {
		
		this.driverId = driverId;
	}

	public void setDriverLicenseNum(String driverLicenseNum) {
		
		this.driverLicenseNum = driverLicenseNum;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Driver comparator = (Driver)anObject;

		if ((this.getDisplayName() != comparator.getDisplayName()) && ((this.getDisplayName() == null) || (! this.getDisplayName().equals(comparator.getDisplayName())))) return false;
		if ((this.getIdCardNo() != comparator.getIdCardNo()) && ((this.getIdCardNo() == null) || (! this.getIdCardNo().equals(comparator.getIdCardNo())))) return false;
		if ((this.getGender() != comparator.getGender()) && ((this.getGender() == null) || (! this.getGender().equals(comparator.getGender())))) return false;
		if ((this.getDriverId() != comparator.getDriverId()) && ((this.getDriverId() == null) || (! this.getDriverId().equals(comparator.getDriverId())))) return false;
		if ((this.getDriverLicenseNum() != comparator.getDriverLicenseNum()) && ((this.getDriverLicenseNum() == null) || (! this.getDriverLicenseNum().equals(comparator.getDriverLicenseNum())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 5531;

		hash = 2503 * hash + (null == this.getDisplayName() ? 0 : this.getDisplayName().hashCode());
		hash = 1483 * hash + (null == this.getIdCardNo() ? 0 : this.getIdCardNo().hashCode());
		hash = 2659 * hash + (null == this.getGender() ? 0 : this.getGender().hashCode());
		hash = 7727 * hash + (null == this.getDriverId() ? 0 : this.getDriverId().hashCode());
		hash = 383 * hash + (null == this.getDriverLicenseNum() ? 0 : this.getDriverLicenseNum().hashCode());
		return hash;
	}

}
