/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class ECUDiagnostic extends Object {
	public ECUDiagnostic() {
	}

	private String ecuID;

	private Long exceptionCode;

	private List<DiagnosticTroubleCode> dtcs;

	private HealthStatus diagnosticResult;

	public String getEcuID() {
		
		return this.ecuID;
	}
	
	public Long getExceptionCode() {
		
		return this.exceptionCode;
	}
	
	public List<DiagnosticTroubleCode> getDtcs() {
		
		return this.dtcs;
	}
	
	public HealthStatus getDiagnosticResult() {
		
		return this.diagnosticResult;
	}
	
	public void setEcuID(String ecuID) {
		
		this.ecuID = ecuID;
	}

	public void setExceptionCode(Long exceptionCode) {
		
		this.exceptionCode = exceptionCode;
	}

	public void setDtcs(List<DiagnosticTroubleCode> dtcs) {
		
		this.dtcs = dtcs;
	}

	public void setDiagnosticResult(HealthStatus diagnosticResult) {
		
		this.diagnosticResult = diagnosticResult;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		ECUDiagnostic comparator = (ECUDiagnostic)anObject;

		if ((this.getEcuID() != comparator.getEcuID()) && ((this.getEcuID() == null) || (! this.getEcuID().equals(comparator.getEcuID())))) return false;
		if ((this.getExceptionCode() != comparator.getExceptionCode()) && ((this.getExceptionCode() == null) || (! this.getExceptionCode().equals(comparator.getExceptionCode())))) return false;
		if ((this.getDtcs() != comparator.getDtcs()) && ((this.getDtcs() == null) || (! this.getDtcs().equals(comparator.getDtcs())))) return false;
		if ((this.getDiagnosticResult() != comparator.getDiagnosticResult()) && ((this.getDiagnosticResult() == null) || (! this.getDiagnosticResult().equals(comparator.getDiagnosticResult())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 2357;

		hash = 5233 * hash + (null == this.getEcuID() ? 0 : this.getEcuID().hashCode());
		hash = 2749 * hash + (null == this.getExceptionCode() ? 0 : this.getExceptionCode().hashCode());
		hash = 6529 * hash + (null == this.getDtcs() ? 0 : this.getDtcs().hashCode());
		hash = 2213 * hash + (null == this.getDiagnosticResult() ? 0 : this.getDiagnosticResult().hashCode());
		return hash;
	}

}
