/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Event extends Object {
	public Event() {
	}

	private EventPayload eventPayload;

	private String type;

	private IdString id;

	private String name;

	private String description;

	private TimeStamp timestamp;

	public EventPayload getEventPayload() {
		
		return this.eventPayload;
	}
	
	public String getType() {
		
		return this.type;
	}
	
	public IdString getId() {
		
		return this.id;
	}
	
	public String getName() {
		
		return this.name;
	}
	
	public String getDescription() {
		
		return this.description;
	}
	
	public TimeStamp getTimestamp() {
		
		return this.timestamp;
	}
	
	public void setEventPayload(EventPayload eventPayload) {
		
		this.eventPayload = eventPayload;
	}

	public void setType(String type) {
		
		this.type = type;
	}

	public void setId(IdString id) {
		
		this.id = id;
	}

	public void setName(String name) {
		
		this.name = name;
	}

	public void setDescription(String description) {
		
		this.description = description;
	}

	public void setTimestamp(TimeStamp timestamp) {
		
		this.timestamp = timestamp;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Event comparator = (Event)anObject;

		if ((this.getEventPayload() != comparator.getEventPayload()) && ((this.getEventPayload() == null) || (! this.getEventPayload().equals(comparator.getEventPayload())))) return false;
		if ((this.getType() != comparator.getType()) && ((this.getType() == null) || (! this.getType().equals(comparator.getType())))) return false;
		if ((this.getId() != comparator.getId()) && ((this.getId() == null) || (! this.getId().equals(comparator.getId())))) return false;
		if ((this.getName() != comparator.getName()) && ((this.getName() == null) || (! this.getName().equals(comparator.getName())))) return false;
		if ((this.getDescription() != comparator.getDescription()) && ((this.getDescription() == null) || (! this.getDescription().equals(comparator.getDescription())))) return false;
		if ((this.getTimestamp() != comparator.getTimestamp()) && ((this.getTimestamp() == null) || (! this.getTimestamp().equals(comparator.getTimestamp())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 5477;

		hash = 3539 * hash + (null == this.getEventPayload() ? 0 : this.getEventPayload().hashCode());
		hash = 6473 * hash + (null == this.getType() ? 0 : this.getType().hashCode());
		hash = 3911 * hash + (null == this.getId() ? 0 : this.getId().hashCode());
		hash = 137 * hash + (null == this.getName() ? 0 : this.getName().hashCode());
		hash = 3697 * hash + (null == this.getDescription() ? 0 : this.getDescription().hashCode());
		hash = 1493 * hash + (null == this.getTimestamp() ? 0 : this.getTimestamp().hashCode());
		return hash;
	}

}
