/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Header extends Object {
	public Header() {
	}

	private IdString requestid;

	private Boolean ackRequired;

	private String imei;

	private String imsi;

	private String msisdn;

	private String vin;

	private TimeStamp timeStamp;

	public IdString getRequestid() {
		
		return this.requestid;
	}
	
	public Boolean getAckRequired() {
		
		return this.ackRequired;
	}
	
	public String getImei() {
		
		return this.imei;
	}
	
	public String getImsi() {
		
		return this.imsi;
	}
	
	public String getMsisdn() {
		
		return this.msisdn;
	}
	
	public String getVin() {
		
		return this.vin;
	}
	
	public TimeStamp getTimeStamp() {
		
		return this.timeStamp;
	}
	
	public void setRequestid(IdString requestid) {
		
		this.requestid = requestid;
	}

	public void setAckRequired(Boolean ackRequired) {
		
		this.ackRequired = ackRequired;
	}

	public void setImei(String imei) {
		
		this.imei = imei;
	}

	public void setImsi(String imsi) {
		
		this.imsi = imsi;
	}

	public void setMsisdn(String msisdn) {
		
		this.msisdn = msisdn;
	}

	public void setVin(String vin) {
		
		this.vin = vin;
	}

	public void setTimeStamp(TimeStamp timeStamp) {
		
		this.timeStamp = timeStamp;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Header comparator = (Header)anObject;

		if ((this.getRequestid() != comparator.getRequestid()) && ((this.getRequestid() == null) || (! this.getRequestid().equals(comparator.getRequestid())))) return false;
		if ((this.getAckRequired() != comparator.getAckRequired()) && ((this.getAckRequired() == null) || (! this.getAckRequired().equals(comparator.getAckRequired())))) return false;
		if ((this.getImei() != comparator.getImei()) && ((this.getImei() == null) || (! this.getImei().equals(comparator.getImei())))) return false;
		if ((this.getImsi() != comparator.getImsi()) && ((this.getImsi() == null) || (! this.getImsi().equals(comparator.getImsi())))) return false;
		if ((this.getMsisdn() != comparator.getMsisdn()) && ((this.getMsisdn() == null) || (! this.getMsisdn().equals(comparator.getMsisdn())))) return false;
		if ((this.getVin() != comparator.getVin()) && ((this.getVin() == null) || (! this.getVin().equals(comparator.getVin())))) return false;
		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 6133;

		hash = 5437 * hash + (null == this.getRequestid() ? 0 : this.getRequestid().hashCode());
		hash = 6563 * hash + (null == this.getAckRequired() ? 0 : this.getAckRequired().hashCode());
		hash = 7027 * hash + (null == this.getImei() ? 0 : this.getImei().hashCode());
		hash = 3229 * hash + (null == this.getImsi() ? 0 : this.getImsi().hashCode());
		hash = 3361 * hash + (null == this.getMsisdn() ? 0 : this.getMsisdn().hashCode());
		hash = 4051 * hash + (null == this.getVin() ? 0 : this.getVin().hashCode());
		hash = 5237 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		return hash;
	}

}
