/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class IdString extends Object {
	public IdString() {
	}

	private String IdString;

	public IdString(String value) {
		this.setIdString(value);
	};


	public String getIdString() {
		
		return this.IdString;
	}
	
	public void setIdString(String IdString) {
		
		this.IdString = IdString;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		IdString comparator = (IdString)anObject;

		if ((this.getIdString() != comparator.getIdString()) && ((this.getIdString() == null) || (! this.getIdString().equals(comparator.getIdString())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 5189;

		hash = 1931 * hash + (null == this.getIdString() ? 0 : this.getIdString().hashCode());
		return hash;
	}

}
