/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class MilElement extends Object {
	public MilElement() {
	}

	private MilCode mil;

	private MilStatus status;

	public MilCode getMil() {
		
		return this.mil;
	}
	
	public MilStatus getStatus() {
		
		return this.status;
	}
	
	public void setMil(MilCode mil) {
		
		this.mil = mil;
	}

	public void setStatus(MilStatus status) {
		
		this.status = status;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		MilElement comparator = (MilElement)anObject;

		if ((this.getMil() != comparator.getMil()) && ((this.getMil() == null) || (! this.getMil().equals(comparator.getMil())))) return false;
		if ((this.getStatus() != comparator.getStatus()) && ((this.getStatus() == null) || (! this.getStatus().equals(comparator.getStatus())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 173;

		hash = 7561 * hash + (null == this.getMil() ? 0 : this.getMil().hashCode());
		hash = 1103 * hash + (null == this.getStatus() ? 0 : this.getStatus().hashCode());
		return hash;
	}

}
