/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Passengers extends Object {
	public Passengers() {
	}

	private String customerPhoneNum;

	private String customerName;

	private Contact contact;

	public String getCustomerPhoneNum() {
		
		return this.customerPhoneNum;
	}
	
	public String getCustomerName() {
		
		return this.customerName;
	}
	
	public Contact getContact() {
		
		return this.contact;
	}
	
	public void setCustomerPhoneNum(String customerPhoneNum) {
		
		this.customerPhoneNum = customerPhoneNum;
	}

	public void setCustomerName(String customerName) {
		
		this.customerName = customerName;
	}

	public void setContact(Contact contact) {
		
		this.contact = contact;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Passengers comparator = (Passengers)anObject;

		if ((this.getCustomerPhoneNum() != comparator.getCustomerPhoneNum()) && ((this.getCustomerPhoneNum() == null) || (! this.getCustomerPhoneNum().equals(comparator.getCustomerPhoneNum())))) return false;
		if ((this.getCustomerName() != comparator.getCustomerName()) && ((this.getCustomerName() == null) || (! this.getCustomerName().equals(comparator.getCustomerName())))) return false;
		if ((this.getContact() != comparator.getContact()) && ((this.getContact() == null) || (! this.getContact().equals(comparator.getContact())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 331;

		hash = 3079 * hash + (null == this.getCustomerPhoneNum() ? 0 : this.getCustomerPhoneNum().hashCode());
		hash = 4513 * hash + (null == this.getCustomerName() ? 0 : this.getCustomerName().hashCode());
		hash = 677 * hash + (null == this.getContact() ? 0 : this.getContact().hashCode());
		return hash;
	}

}
