/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class PassengerOn extends Object {
	public PassengerOn() {
	}

	private Position position;

	private Long passengerCount;

	private String passengerStatus;

	private String driverIdNum;

	private String driverLicenseNum;

	private String driverPhoneNum;

	private String companyName;

	private String customerPhoneNum;

	private String customerName;

	public Position getPosition() {
		
		return this.position;
	}
	
	public Long getPassengerCount() {
		
		return this.passengerCount;
	}
	
	public String getPassengerStatus() {
		
		return this.passengerStatus;
	}
	
	public String getDriverIdNum() {
		
		return this.driverIdNum;
	}
	
	public String getDriverLicenseNum() {
		
		return this.driverLicenseNum;
	}
	
	public String getDriverPhoneNum() {
		
		return this.driverPhoneNum;
	}
	
	public String getCompanyName() {
		
		return this.companyName;
	}
	
	public String getCustomerPhoneNum() {
		
		return this.customerPhoneNum;
	}
	
	public String getCustomerName() {
		
		return this.customerName;
	}
	
	public void setPosition(Position position) {
		
		this.position = position;
	}

	public void setPassengerCount(Long passengerCount) {
		
		this.passengerCount = passengerCount;
	}

	public void setPassengerStatus(String passengerStatus) {
		
		this.passengerStatus = passengerStatus;
	}

	public void setDriverIdNum(String driverIdNum) {
		
		this.driverIdNum = driverIdNum;
	}

	public void setDriverLicenseNum(String driverLicenseNum) {
		
		this.driverLicenseNum = driverLicenseNum;
	}

	public void setDriverPhoneNum(String driverPhoneNum) {
		
		this.driverPhoneNum = driverPhoneNum;
	}

	public void setCompanyName(String companyName) {
		
		this.companyName = companyName;
	}

	public void setCustomerPhoneNum(String customerPhoneNum) {
		
		this.customerPhoneNum = customerPhoneNum;
	}

	public void setCustomerName(String customerName) {
		
		this.customerName = customerName;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		PassengerOn comparator = (PassengerOn)anObject;

		if ((this.getPosition() != comparator.getPosition()) && ((this.getPosition() == null) || (! this.getPosition().equals(comparator.getPosition())))) return false;
		if ((this.getPassengerCount() != comparator.getPassengerCount()) && ((this.getPassengerCount() == null) || (! this.getPassengerCount().equals(comparator.getPassengerCount())))) return false;
		if ((this.getPassengerStatus() != comparator.getPassengerStatus()) && ((this.getPassengerStatus() == null) || (! this.getPassengerStatus().equals(comparator.getPassengerStatus())))) return false;
		if ((this.getDriverIdNum() != comparator.getDriverIdNum()) && ((this.getDriverIdNum() == null) || (! this.getDriverIdNum().equals(comparator.getDriverIdNum())))) return false;
		if ((this.getDriverLicenseNum() != comparator.getDriverLicenseNum()) && ((this.getDriverLicenseNum() == null) || (! this.getDriverLicenseNum().equals(comparator.getDriverLicenseNum())))) return false;
		if ((this.getDriverPhoneNum() != comparator.getDriverPhoneNum()) && ((this.getDriverPhoneNum() == null) || (! this.getDriverPhoneNum().equals(comparator.getDriverPhoneNum())))) return false;
		if ((this.getCompanyName() != comparator.getCompanyName()) && ((this.getCompanyName() == null) || (! this.getCompanyName().equals(comparator.getCompanyName())))) return false;
		if ((this.getCustomerPhoneNum() != comparator.getCustomerPhoneNum()) && ((this.getCustomerPhoneNum() == null) || (! this.getCustomerPhoneNum().equals(comparator.getCustomerPhoneNum())))) return false;
		if ((this.getCustomerName() != comparator.getCustomerName()) && ((this.getCustomerName() == null) || (! this.getCustomerName().equals(comparator.getCustomerName())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 3929;

		hash = 6991 * hash + (null == this.getPosition() ? 0 : this.getPosition().hashCode());
		hash = 4957 * hash + (null == this.getPassengerCount() ? 0 : this.getPassengerCount().hashCode());
		hash = 1399 * hash + (null == this.getPassengerStatus() ? 0 : this.getPassengerStatus().hashCode());
		hash = 7459 * hash + (null == this.getDriverIdNum() ? 0 : this.getDriverIdNum().hashCode());
		hash = 3541 * hash + (null == this.getDriverLicenseNum() ? 0 : this.getDriverLicenseNum().hashCode());
		hash = 5519 * hash + (null == this.getDriverPhoneNum() ? 0 : this.getDriverPhoneNum().hashCode());
		hash = 587 * hash + (null == this.getCompanyName() ? 0 : this.getCompanyName().hashCode());
		hash = 6343 * hash + (null == this.getCustomerPhoneNum() ? 0 : this.getCustomerPhoneNum().hashCode());
		hash = 2909 * hash + (null == this.getCustomerName() ? 0 : this.getCustomerName().hashCode());
		return hash;
	}

}
