/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class PositionNSpeed extends Object {
	public PositionNSpeed() {
	}

	private Double latitude;

	private Double longitude;

	private Double altitude;

	private Double heading;

	private Long fix;

	private Double speed;

	public Double getLatitude() {
		
		return this.latitude;
	}
	
	public Double getLongitude() {
		
		return this.longitude;
	}
	
	public Double getAltitude() {
		
		return this.altitude;
	}
	
	public Double getHeading() {
		
		return this.heading;
	}
	
	public Long getFix() {
		
		return this.fix;
	}
	
	public Double getSpeed() {
		
		return this.speed;
	}
	
	public void setLatitude(Double latitude) {
		
		this.latitude = latitude;
	}

	public void setLongitude(Double longitude) {
		
		this.longitude = longitude;
	}

	public void setAltitude(Double altitude) {
		
		this.altitude = altitude;
	}

	public void setHeading(Double heading) {
		
		this.heading = heading;
	}

	public void setFix(Long fix) {
		
		this.fix = fix;
	}

	public void setSpeed(Double speed) {
		
		this.speed = speed;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		PositionNSpeed comparator = (PositionNSpeed)anObject;

		if ((this.getLatitude() != comparator.getLatitude()) && ((this.getLatitude() == null) || (! this.getLatitude().equals(comparator.getLatitude())))) return false;
		if ((this.getLongitude() != comparator.getLongitude()) && ((this.getLongitude() == null) || (! this.getLongitude().equals(comparator.getLongitude())))) return false;
		if ((this.getAltitude() != comparator.getAltitude()) && ((this.getAltitude() == null) || (! this.getAltitude().equals(comparator.getAltitude())))) return false;
		if ((this.getHeading() != comparator.getHeading()) && ((this.getHeading() == null) || (! this.getHeading().equals(comparator.getHeading())))) return false;
		if ((this.getFix() != comparator.getFix()) && ((this.getFix() == null) || (! this.getFix().equals(comparator.getFix())))) return false;
		if ((this.getSpeed() != comparator.getSpeed()) && ((this.getSpeed() == null) || (! this.getSpeed().equals(comparator.getSpeed())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 1861;

		hash = 3581 * hash + (null == this.getLatitude() ? 0 : this.getLatitude().hashCode());
		hash = 2971 * hash + (null == this.getLongitude() ? 0 : this.getLongitude().hashCode());
		hash = 6043 * hash + (null == this.getAltitude() ? 0 : this.getAltitude().hashCode());
		hash = 859 * hash + (null == this.getHeading() ? 0 : this.getHeading().hashCode());
		hash = 1117 * hash + (null == this.getFix() ? 0 : this.getFix().hashCode());
		hash = 7187 * hash + (null == this.getSpeed() ? 0 : this.getSpeed().hashCode());
		return hash;
	}

}
