/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Reason extends Object {
	public Reason() {
	}

	private String code;

	private String status;

	private String description;

	public String getCode() {
		
		return this.code;
	}
	
	public String getStatus() {
		
		return this.status;
	}
	
	public String getDescription() {
		
		return this.description;
	}
	
	public void setCode(String code) {
		
		this.code = code;
	}

	public void setStatus(String status) {
		
		this.status = status;
	}

	public void setDescription(String description) {
		
		this.description = description;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Reason comparator = (Reason)anObject;

		if ((this.getCode() != comparator.getCode()) && ((this.getCode() == null) || (! this.getCode().equals(comparator.getCode())))) return false;
		if ((this.getStatus() != comparator.getStatus()) && ((this.getStatus() == null) || (! this.getStatus().equals(comparator.getStatus())))) return false;
		if ((this.getDescription() != comparator.getDescription()) && ((this.getDescription() == null) || (! this.getDescription().equals(comparator.getDescription())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 6529;

		hash = 4019 * hash + (null == this.getCode() ? 0 : this.getCode().hashCode());
		hash = 2383 * hash + (null == this.getStatus() ? 0 : this.getStatus().hashCode());
		hash = 107 * hash + (null == this.getDescription() ? 0 : this.getDescription().hashCode());
		return hash;
	}

}
