/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Running extends Object {
	public Running() {
	}

	private EngineOilLevelStatus engineOilLevelStatus;

	private Double engineOilTemperature;

	private EngineOilPressureWarning engineOilPressureWarning;

	private Double engineCoolantTemperature;

	private EngineCoolantLevelStatus engineCoolantLevelStatus;

	private Double fuelLevel;

	private FuelLevelStatus fuelLevelStatus;

	private Double aveFuelConsumption;

	private Double aveFuelConsumptionInLatestDrivingCycle;

	private Double avgRunningSpeed;

	private BulbStatus bulbStatus;

	private TimeStamp timeStamp;

	public EngineOilLevelStatus getEngineOilLevelStatus() {
		
		return this.engineOilLevelStatus;
	}
	
	public Double getEngineOilTemperature() {
		
		return this.engineOilTemperature;
	}
	
	public EngineOilPressureWarning getEngineOilPressureWarning() {
		
		return this.engineOilPressureWarning;
	}
	
	public Double getEngineCoolantTemperature() {
		
		return this.engineCoolantTemperature;
	}
	
	public EngineCoolantLevelStatus getEngineCoolantLevelStatus() {
		
		return this.engineCoolantLevelStatus;
	}
	
	public Double getFuelLevel() {
		
		return this.fuelLevel;
	}
	
	public FuelLevelStatus getFuelLevelStatus() {
		
		return this.fuelLevelStatus;
	}
	
	public Double getAveFuelConsumption() {
		
		return this.aveFuelConsumption;
	}
	
	public Double getAveFuelConsumptionInLatestDrivingCycle() {
		
		return this.aveFuelConsumptionInLatestDrivingCycle;
	}
	
	public Double getAvgRunningSpeed() {
		
		return this.avgRunningSpeed;
	}
	
	public BulbStatus getBulbStatus() {
		
		return this.bulbStatus;
	}
	
	public TimeStamp getTimeStamp() {
		
		return this.timeStamp;
	}
	
	public void setEngineOilLevelStatus(EngineOilLevelStatus engineOilLevelStatus) {
		
		this.engineOilLevelStatus = engineOilLevelStatus;
	}

	public void setEngineOilTemperature(Double engineOilTemperature) {
		
		this.engineOilTemperature = engineOilTemperature;
	}

	public void setEngineOilPressureWarning(EngineOilPressureWarning engineOilPressureWarning) {
		
		this.engineOilPressureWarning = engineOilPressureWarning;
	}

	public void setEngineCoolantTemperature(Double engineCoolantTemperature) {
		
		this.engineCoolantTemperature = engineCoolantTemperature;
	}

	public void setEngineCoolantLevelStatus(EngineCoolantLevelStatus engineCoolantLevelStatus) {
		
		this.engineCoolantLevelStatus = engineCoolantLevelStatus;
	}

	public void setFuelLevel(Double fuelLevel) {
		
		this.fuelLevel = fuelLevel;
	}

	public void setFuelLevelStatus(FuelLevelStatus fuelLevelStatus) {
		
		this.fuelLevelStatus = fuelLevelStatus;
	}

	public void setAveFuelConsumption(Double aveFuelConsumption) {
		
		this.aveFuelConsumption = aveFuelConsumption;
	}

	public void setAveFuelConsumptionInLatestDrivingCycle(Double aveFuelConsumptionInLatestDrivingCycle) {
		
		this.aveFuelConsumptionInLatestDrivingCycle = aveFuelConsumptionInLatestDrivingCycle;
	}

	public void setAvgRunningSpeed(Double avgRunningSpeed) {
		
		this.avgRunningSpeed = avgRunningSpeed;
	}

	public void setBulbStatus(BulbStatus bulbStatus) {
		
		this.bulbStatus = bulbStatus;
	}

	public void setTimeStamp(TimeStamp timeStamp) {
		
		this.timeStamp = timeStamp;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Running comparator = (Running)anObject;

		if ((this.getEngineOilLevelStatus() != comparator.getEngineOilLevelStatus()) && ((this.getEngineOilLevelStatus() == null) || (! this.getEngineOilLevelStatus().equals(comparator.getEngineOilLevelStatus())))) return false;
		if ((this.getEngineOilTemperature() != comparator.getEngineOilTemperature()) && ((this.getEngineOilTemperature() == null) || (! this.getEngineOilTemperature().equals(comparator.getEngineOilTemperature())))) return false;
		if ((this.getEngineOilPressureWarning() != comparator.getEngineOilPressureWarning()) && ((this.getEngineOilPressureWarning() == null) || (! this.getEngineOilPressureWarning().equals(comparator.getEngineOilPressureWarning())))) return false;
		if ((this.getEngineCoolantTemperature() != comparator.getEngineCoolantTemperature()) && ((this.getEngineCoolantTemperature() == null) || (! this.getEngineCoolantTemperature().equals(comparator.getEngineCoolantTemperature())))) return false;
		if ((this.getEngineCoolantLevelStatus() != comparator.getEngineCoolantLevelStatus()) && ((this.getEngineCoolantLevelStatus() == null) || (! this.getEngineCoolantLevelStatus().equals(comparator.getEngineCoolantLevelStatus())))) return false;
		if ((this.getFuelLevel() != comparator.getFuelLevel()) && ((this.getFuelLevel() == null) || (! this.getFuelLevel().equals(comparator.getFuelLevel())))) return false;
		if ((this.getFuelLevelStatus() != comparator.getFuelLevelStatus()) && ((this.getFuelLevelStatus() == null) || (! this.getFuelLevelStatus().equals(comparator.getFuelLevelStatus())))) return false;
		if ((this.getAveFuelConsumption() != comparator.getAveFuelConsumption()) && ((this.getAveFuelConsumption() == null) || (! this.getAveFuelConsumption().equals(comparator.getAveFuelConsumption())))) return false;
		if ((this.getAveFuelConsumptionInLatestDrivingCycle() != comparator.getAveFuelConsumptionInLatestDrivingCycle()) && ((this.getAveFuelConsumptionInLatestDrivingCycle() == null) || (! this.getAveFuelConsumptionInLatestDrivingCycle().equals(comparator.getAveFuelConsumptionInLatestDrivingCycle())))) return false;
		if ((this.getAvgRunningSpeed() != comparator.getAvgRunningSpeed()) && ((this.getAvgRunningSpeed() == null) || (! this.getAvgRunningSpeed().equals(comparator.getAvgRunningSpeed())))) return false;
		if ((this.getBulbStatus() != comparator.getBulbStatus()) && ((this.getBulbStatus() == null) || (! this.getBulbStatus().equals(comparator.getBulbStatus())))) return false;
		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 6257;

		hash = 349 * hash + (null == this.getEngineOilLevelStatus() ? 0 : this.getEngineOilLevelStatus().hashCode());
		hash = 743 * hash + (null == this.getEngineOilTemperature() ? 0 : this.getEngineOilTemperature().hashCode());
		hash = 3697 * hash + (null == this.getEngineOilPressureWarning() ? 0 : this.getEngineOilPressureWarning().hashCode());
		hash = 6337 * hash + (null == this.getEngineCoolantTemperature() ? 0 : this.getEngineCoolantTemperature().hashCode());
		hash = 4211 * hash + (null == this.getEngineCoolantLevelStatus() ? 0 : this.getEngineCoolantLevelStatus().hashCode());
		hash = 2659 * hash + (null == this.getFuelLevel() ? 0 : this.getFuelLevel().hashCode());
		hash = 283 * hash + (null == this.getFuelLevelStatus() ? 0 : this.getFuelLevelStatus().hashCode());
		hash = 4733 * hash + (null == this.getAveFuelConsumption() ? 0 : this.getAveFuelConsumption().hashCode());
		hash = 2803 * hash + (null == this.getAveFuelConsumptionInLatestDrivingCycle() ? 0 : this.getAveFuelConsumptionInLatestDrivingCycle().hashCode());
		hash = 787 * hash + (null == this.getAvgRunningSpeed() ? 0 : this.getAvgRunningSpeed().hashCode());
		hash = 4801 * hash + (null == this.getBulbStatus() ? 0 : this.getBulbStatus().hashCode());
		hash = 2897 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		return hash;
	}

}
