/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class SalikPasses extends Object {
	public SalikPasses() {
	}

	private String salikId;

	private List<Double> coordinate;

	private String passTime;

	public String getSalikId() {
		
		return this.salikId;
	}
	
	public List<Double> getCoordinate() {
		
		return this.coordinate;
	}
	
	public String getPassTime() {
		
		return this.passTime;
	}
	
	public void setSalikId(String salikId) {
		
		this.salikId = salikId;
	}

	public void setCoordinate(List<Double> coordinate) {
		
		this.coordinate = coordinate;
	}

	public void setPassTime(String passTime) {
		
		this.passTime = passTime;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		SalikPasses comparator = (SalikPasses)anObject;

		if ((this.getSalikId() != comparator.getSalikId()) && ((this.getSalikId() == null) || (! this.getSalikId().equals(comparator.getSalikId())))) return false;
		if ((this.getCoordinate() != comparator.getCoordinate()) && ((this.getCoordinate() == null) || (! this.getCoordinate().equals(comparator.getCoordinate())))) return false;
		if ((this.getPassTime() != comparator.getPassTime()) && ((this.getPassTime() == null) || (! this.getPassTime().equals(comparator.getPassTime())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 3571;

		hash = 4649 * hash + (null == this.getSalikId() ? 0 : this.getSalikId().hashCode());
		hash = 4297 * hash + (null == this.getCoordinate() ? 0 : this.getCoordinate().hashCode());
		hash = 3457 * hash + (null == this.getPassTime() ? 0 : this.getPassTime().hashCode());
		return hash;
	}

}
