/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Telematics extends Object {
	public Telematics() {
	}

	private Header header;

	private Body body;

	public Header getHeader() {
		
		return this.header;
	}
	
	public Body getBody() {
		
		return this.body;
	}
	
	public void setHeader(Header header) {
		
		this.header = header;
	}

	public void setBody(Body body) {
		
		this.body = body;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Telematics comparator = (Telematics)anObject;

		if ((this.getHeader() != comparator.getHeader()) && ((this.getHeader() == null) || (! this.getHeader().equals(comparator.getHeader())))) return false;
		if ((this.getBody() != comparator.getBody()) && ((this.getBody() == null) || (! this.getBody().equals(comparator.getBody())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 7193;

		hash = 4987 * hash + (null == this.getHeader() ? 0 : this.getHeader().hashCode());
		hash = 6143 * hash + (null == this.getBody() ? 0 : this.getBody().hashCode());
		return hash;
	}

}
