/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class Theft extends Object {
	public Theft() {
	}

	private Position position;

	private Double odometer;

	public Position getPosition() {
		
		return this.position;
	}
	
	public Double getOdometer() {
		
		return this.odometer;
	}
	
	public void setPosition(Position position) {
		
		this.position = position;
	}

	public void setOdometer(Double odometer) {
		
		this.odometer = odometer;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		Theft comparator = (Theft)anObject;

		if ((this.getPosition() != comparator.getPosition()) && ((this.getPosition() == null) || (! this.getPosition().equals(comparator.getPosition())))) return false;
		if ((this.getOdometer() != comparator.getOdometer()) && ((this.getOdometer() == null) || (! this.getOdometer().equals(comparator.getOdometer())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 1459;

		hash = 3319 * hash + (null == this.getPosition() ? 0 : this.getPosition().hashCode());
		hash = 1601 * hash + (null == this.getOdometer() ? 0 : this.getOdometer().hashCode());
		return hash;
	}

}
