/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.om;

import java.util.List;

public class TimeStamp extends Object {
	public TimeStamp() {
	}

	private Long TimeStamp;

	public TimeStamp(Long value) {
		this.setTimeStamp(value);
	};


	public Long getTimeStamp() {
		
		return this.TimeStamp;
	}
	
	public void setTimeStamp(Long TimeStamp) {
		
		this.TimeStamp = TimeStamp;
	}

	@Override
	public boolean equals(Object anObject) {
		if (this == anObject) return true;
		if ((anObject == null) || (anObject.getClass() != this.getClass())) return false;

		TimeStamp comparator = (TimeStamp)anObject;

		if ((this.getTimeStamp() != comparator.getTimeStamp()) && ((this.getTimeStamp() == null) || (! this.getTimeStamp().equals(comparator.getTimeStamp())))) return false;
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 5107;

		hash = 4657 * hash + (null == this.getTimeStamp() ? 0 : this.getTimeStamp().hashCode());
		return hash;
	}

}
