/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import static org.openasn1.codec.coder.TagClass.*;
import static org.openasn1.codec.coder.TaggingMode.*;

import org.openasn1.codec.coder.Tag;
import org.openasn1.codec.coder.TagClass;
import org.openasn1.codec.coder.typecoder.*;
import org.openasn1.codec.constraints.*;
import org.openasn1.codec.constraints.subtype.*;

import Telematics.om.*;
public final class BodyTypeInformation {
	static private TypeInformation typeInformation;
	
	
	
	private BodyTypeInformation() { }
	
	/**
	 * Static class initialisation. 
	 * Fill and set type information
	 */
	static {
    	typeInformation = new TypeInformation();
    	
    	ArrayList<Tag> tagList = new ArrayList<Tag>();
    	typeInformation.setTagList(tagList);
    	
    	typeInformation.setExtensible(false);
	}

	public static class _basicTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 0));
			getTypeInformation().getTagList().addAll(BasicTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(BasicTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _maintenanceTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 1));
			getTypeInformation().getTagList().addAll(MaintenanceTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(MaintenanceTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _runningTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 2));
			getTypeInformation().getTagList().addAll(RunningTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(RunningTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _drivingSafetyTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 3));
			getTypeInformation().getTagList().addAll(DrivingSafetyTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DrivingSafetyTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _drivingBehaviorTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 4));
			getTypeInformation().getTagList().addAll(DrivingBehaviorTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DrivingBehaviorTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _diagnosticsTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 5));
			getTypeInformation().getTagList().addAll(DiagnosticsTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DiagnosticsTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _eventTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 6));
			getTypeInformation().getTagList().addAll(EventTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(EventTypeInformation.getTypeInformation().getConstraint());
		}
	}


	static public TypeInformation getTypeInformation() {
    	return typeInformation; 
    }
}
