/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import org.openasn1.codec.coder.ASN1Encoder;
import org.openasn1.codec.coder.typecoder.*;
import Telematics.om.*;

public class DiagnosticTroubleCodeEncoder extends TypeEncoder<DiagnosticTroubleCode> {
	public DiagnosticTroubleCodeEncoder(DiagnosticTroubleCode encodable, TypeInformation typeInformation) {
		super(encodable, typeInformation);
	}
	HashMap<DtcStatus, EnumeratedItemTypeInformation> enumTypeMapDtcStatus = DtcStatusTypeInformation.getEnumTypeMap();
	HashMap<OdoStatus, EnumeratedItemTypeInformation> enumTypeMapOdoStatus = OdoStatusTypeInformation.getEnumTypeMap();
	@Override
	public void encode(ASN1Encoder encoder) throws IOException {
		ArrayList<TypeEncoder> componentEncoderList = new ArrayList<TypeEncoder>();

		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getDtc(), DiagnosticTroubleCodeTypeInformation._dtcTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getDtcAdvice(), DiagnosticTroubleCodeTypeInformation._dtcAdviceTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getDtcDesc(), DiagnosticTroubleCodeTypeInformation._dtcDescTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new TimeStampEncoder(getEncodable().getFirstFail(), DiagnosticTroubleCodeTypeInformation._firstFailTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new TimeStampEncoder(getEncodable().getLastFail(), DiagnosticTroubleCodeTypeInformation._lastFailTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new DtcStatusEncoder(enumTypeMapDtcStatus, getEncodable().getStatus(), DiagnosticTroubleCodeTypeInformation._statusTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getOdometer(), DiagnosticTroubleCodeTypeInformation._odometerTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new OdoStatusEncoder(enumTypeMapOdoStatus, getEncodable().getOdoStatus(), DiagnosticTroubleCodeTypeInformation._odoStatusTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new RealEncoder(getEncodable().getFailureBatteryVoltage(), DiagnosticTroubleCodeTypeInformation._failureBatteryVoltageTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new RealEncoder(getEncodable().getFailureVehicleSpeed(), DiagnosticTroubleCodeTypeInformation._failureVehicleSpeedTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PositionEncoder(getEncodable().getPosition(), DiagnosticTroubleCodeTypeInformation._positionTypeInformation.getTypeInformation())
);

		encoder.encodeAsSet(componentEncoderList, getTypeInformation());
	}
}
