/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import static org.openasn1.codec.coder.TagClass.*;
import static org.openasn1.codec.coder.TaggingMode.*;

import org.openasn1.codec.coder.Tag;
import org.openasn1.codec.coder.TagClass;
import org.openasn1.codec.coder.typecoder.*;
import org.openasn1.codec.constraints.*;
import org.openasn1.codec.constraints.subtype.*;

import Telematics.om.*;
public final class DrivingSafetyTypeInformation {
	static private TypeInformation typeInformation;
	
	
	
	private DrivingSafetyTypeInformation() { }
	
	/**
	 * Static class initialisation. 
	 * Fill and set type information
	 */
	static {
    	typeInformation = new TypeInformation();
    	
    	ArrayList<Tag> tagList = new ArrayList<Tag>();
    	typeInformation.setTagList(tagList);
    	
    	typeInformation.setExtensible(false);
	}

	public static class _srsStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 0));
			getTypeInformation().getTagList().addAll(SrsStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(SrsStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorOpenStatusDriverTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 1));
			getTypeInformation().getTagList().addAll(DoorStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorOpenStatusPassengerTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 2));
			getTypeInformation().getTagList().addAll(DoorStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorOpenStatusDriverRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 3));
			getTypeInformation().getTagList().addAll(DoorStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorOpenStatusPassengerRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 4));
			getTypeInformation().getTagList().addAll(DoorStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorLockStatusDriverTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 5));
			getTypeInformation().getTagList().addAll(DoorLockedStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorLockedStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorLockStatusPassengerTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 6));
			getTypeInformation().getTagList().addAll(DoorLockedStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorLockedStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorLockStatusDriverRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 7));
			getTypeInformation().getTagList().addAll(DoorLockedStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorLockedStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _doorLockStatusPassengerRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 8));
			getTypeInformation().getTagList().addAll(DoorLockedStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(DoorLockedStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _seatBeltStatusDriverTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 9));
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
		}
	}

	public static class _seatBeltStatusPassengerTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 10));
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
		}
	}

	public static class _seatBeltStatusDriverRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 11));
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
		}
	}

	public static class _seatBeltStatusPassengerRearTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 12));
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
		}
	}

	public static class _handBrakeStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 13));
			getTypeInformation().getTagList().addAll(HandBrakeStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(HandBrakeStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _electricParkBrakeStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 14));
			getTypeInformation().getTagList().addAll(ElectricParkBrakeStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(ElectricParkBrakeStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _timeStampTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 15));
			getTypeInformation().getTagList().addAll(TimeStampTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(TimeStampTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _trunkOpenStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 16));
			getTypeInformation().getTagList().addAll(TrunkStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(TrunkStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _engineHoodOpenStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 17));
			getTypeInformation().getTagList().addAll(EngineHoodStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(EngineHoodStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}

	public static class _centralLockingStatusTypeInformation {
		private static TypeInformation typeInformation = new TypeInformation();
		
		public static TypeInformation getTypeInformation() { return typeInformation; }
		
		
		static {
			getTypeInformation().setTagList(new ArrayList<Tag>());
			getTypeInformation().getTagList().add(new Tag(IMPLICIT, CONTEXT_SPECIFIC, 18));
			getTypeInformation().getTagList().addAll(CentralLockingStatusTypeInformation.getTypeInformation().getTagList());
			getTypeInformation().setExtensible(false);
			getTypeInformation().setOptional(true);
			getTypeInformation().setConstraint(CentralLockingStatusTypeInformation.getTypeInformation().getConstraint());
		}
	}


	static public TypeInformation getTypeInformation() {
    	return typeInformation; 
    }
}
