/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import org.openasn1.codec.coder.ASN1Encoder;
import org.openasn1.codec.coder.typecoder.*;
import Telematics.om.*;

public class PassengersEncoder extends TypeEncoder<Passengers> {
	public PassengersEncoder(Passengers encodable, TypeInformation typeInformation) {
		super(encodable, typeInformation);
	}
	HashMap<Contact,EnumeratedItemTypeInformation> enumTypeContact = ContactTypeInformation.getEnumTypeMap();
	
	@Override
	public void encode(ASN1Encoder encoder) throws IOException {
		ArrayList<TypeEncoder> componentEncoderList = new ArrayList<TypeEncoder>();

		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getCustomerPhoneNum(), PassengersTypeInformation._customerPhoneNumTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getCustomerName(), PassengersTypeInformation._customerNameTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new ContactEncoder(enumTypeContact, getEncodable().getContact(), PassengersTypeInformation._contactTypeInformation.getTypeInformation())
);

		encoder.encodeAsSet(componentEncoderList, getTypeInformation());
	}
}
