/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import static org.openasn1.codec.coder.TagClass.*;
import static org.openasn1.codec.coder.TaggingMode.*;

import org.openasn1.codec.coder.Tag;
import org.openasn1.codec.coder.TagClass;
import org.openasn1.codec.coder.typecoder.*;
import org.openasn1.codec.constraints.*;
import org.openasn1.codec.constraints.subtype.*;

import Telematics.om.*;
public final class TransimissionGearPostionTypeInformation {
	static private TypeInformation typeInformation;
	static private HashMap<TransimissionGearPostion, EnumeratedItemTypeInformation> enumTypeMap = new HashMap<TransimissionGearPostion, EnumeratedItemTypeInformation>();
	public static HashMap<TransimissionGearPostion, EnumeratedItemTypeInformation> getEnumTypeMap() { return enumTypeMap; }
	
	private TransimissionGearPostionTypeInformation() { }
	
	/**
	 * Static class initialisation. 
	 * Fill and set type information
	 */
	static {
    	typeInformation = new TypeInformation();
    	
    	ArrayList<Tag> tagList = new ArrayList<Tag>();
    	typeInformation.setTagList(tagList);
		
		TransimissionGearPostion enumeration = null;
		enumTypeMap.put(enumeration.notDisplayed, new EnumeratedItemTypeInformation(false, 0));
		enumTypeMap.put(enumeration.pPosition, new EnumeratedItemTypeInformation(false, 1));
		enumTypeMap.put(enumeration.rPosition, new EnumeratedItemTypeInformation(false, 2));
		enumTypeMap.put(enumeration.nPosition, new EnumeratedItemTypeInformation(false, 3));
		enumTypeMap.put(enumeration.dPosition, new EnumeratedItemTypeInformation(false, 4));
		enumTypeMap.put(enumeration.m1Position, new EnumeratedItemTypeInformation(false, 5));
		enumTypeMap.put(enumeration.m2Position, new EnumeratedItemTypeInformation(false, 6));
		enumTypeMap.put(enumeration.m3Position, new EnumeratedItemTypeInformation(false, 7));
		enumTypeMap.put(enumeration.m4Position, new EnumeratedItemTypeInformation(false, 8));
		enumTypeMap.put(enumeration.m5Position, new EnumeratedItemTypeInformation(false, 9));
		enumTypeMap.put(enumeration.m6Position, new EnumeratedItemTypeInformation(false, 10));
		enumTypeMap.put(enumeration.m7Position, new EnumeratedItemTypeInformation(false, 11));
		enumTypeMap.put(enumeration.m1PlusPosition, new EnumeratedItemTypeInformation(false, 12));
		enumTypeMap.put(enumeration.m2PlusPosition, new EnumeratedItemTypeInformation(false, 13));
		enumTypeMap.put(enumeration.m3PlusPosition, new EnumeratedItemTypeInformation(false, 14));
		enumTypeMap.put(enumeration.m4PlusPosition, new EnumeratedItemTypeInformation(false, 15));
		enumTypeMap.put(enumeration.m5PlusPosition, new EnumeratedItemTypeInformation(false, 16));
		enumTypeMap.put(enumeration.m6PlusPosition, new EnumeratedItemTypeInformation(false, 17));
		enumTypeMap.put(enumeration.m2MinusPosition, new EnumeratedItemTypeInformation(false, 18));
		enumTypeMap.put(enumeration.m3MinusPosition, new EnumeratedItemTypeInformation(false, 19));
		enumTypeMap.put(enumeration.m4MinusPosition, new EnumeratedItemTypeInformation(false, 20));
		enumTypeMap.put(enumeration.m5MinusPosition, new EnumeratedItemTypeInformation(false, 21));
		enumTypeMap.put(enumeration.m6MinusPosition, new EnumeratedItemTypeInformation(false, 22));
		enumTypeMap.put(enumeration.m7MinusPosition, new EnumeratedItemTypeInformation(false, 23));
    	
    	typeInformation.setExtensible(false);
	}


	static public TypeInformation getTypeInformation() {
    	return typeInformation; 
    }
}
