/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.openasn1.codec.coder.ASN1Encoder;
import org.openasn1.codec.coder.typecoder.*;
import Telematics.om.*;

public class TripStartEncoder extends TypeEncoder<TripStart> {
	public TripStartEncoder(TripStart encodable, TypeInformation typeInformation) {
		super(encodable, typeInformation);
	}
	HashMap<Type,EnumeratedItemTypeInformation> enumTypeType2 = Type2TypeInformation.getEnumTypeMap();
	@Override
	public void encode(ASN1Encoder encoder) throws IOException {
		ArrayList<TypeEncoder> componentEncoderList = new ArrayList<TypeEncoder>();
		ArrayList<Driver> encodablesList2 = new ArrayList<Driver>();
		List<Driver> driver = getEncodable().getDriver();
		encodablesList2.addAll(driver);
		componentEncoderList.add(
new Type2Encoder(enumTypeType2, getEncodable().getType(), TripStartTypeInformation._typeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getStartTime(), TripStartTypeInformation._startTimeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PositionEncoder(getEncodable().getStartPosition(), TripStartTypeInformation._startPositionTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getOdometer(), TripStartTypeInformation._odometerTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new CustomerEncoder(getEncodable().getCustomer(), TripStartTypeInformation._customerTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getEnterpriseName(), TripStartTypeInformation._enterpriseNameTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new SetOfEncoder<Driver>(
new DriverEncoder(null, TripStartTypeInformation._driverTypeInformation.__driverTypeInformation.getTypeInformation())
, encodablesList2, TripStartTypeInformation._driverTypeInformation.getTypeInformation())
);

		encoder.encodeAsSet(componentEncoderList, getTypeInformation());
	}
}
