/*  
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as 
 *   published by the Free Software Foundation, either version 3 of 
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package Telematics.coder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.openasn1.codec.coder.ASN1Encoder;
import org.openasn1.codec.coder.typecoder.*;
import Telematics.om.*;

public class TripEndEncoder extends TypeEncoder<TripEnd> {
	public TripEndEncoder(TripEnd encodable, TypeInformation typeInformation) {
		super(encodable, typeInformation);
	}
	HashMap<Type,EnumeratedItemTypeInformation> enumTypeType2 = Type2TypeInformation.getEnumTypeMap();
	@Override
	public void encode(ASN1Encoder encoder) throws IOException {
		ArrayList<TypeEncoder> componentEncoderList = new ArrayList<TypeEncoder>();
		ArrayList<SalikPasses> encodablesList1 = new ArrayList<SalikPasses>();
		List<SalikPasses> salikpass = getEncodable().getSalikPasses();
		encodablesList1.addAll(salikpass);
		ArrayList<Driver> encodablesList2 = new ArrayList<Driver>();
		List<Driver> driver = getEncodable().getDriver();
		encodablesList2.addAll(driver);

		componentEncoderList.add(
new Type2Encoder(enumTypeType2, getEncodable().getType(), TripEndTypeInformation._typeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getStartTime(), TripEndTypeInformation._startTimeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PositionEncoder(getEncodable().getStartPosition(), TripEndTypeInformation._startPositionTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getEndTime(), TripEndTypeInformation._endTimeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PositionEncoder(getEncodable().getEndPosition(), TripEndTypeInformation._endPositionTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getDistance(), TripEndTypeInformation._distanceTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getTripTime(), TripEndTypeInformation._tripTimeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new FareEncoder(getEncodable().getFare(), TripEndTypeInformation._fareTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new SetOfEncoder<SalikPasses>(
new SalikPassesEncoder(null, TripEndTypeInformation._salikPassesTypeInformation.__salikPassesTypeInformation.getTypeInformation())
, encodablesList1, TripEndTypeInformation._salikPassesTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getPaymentType(), TripEndTypeInformation._paymentTypeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getMaxSpeed(), TripEndTypeInformation._maxSpeedTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getAverageSpeed(), TripEndTypeInformation._averageSpeedTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new RealEncoder(getEncodable().getAverageFuelConsumption(), TripEndTypeInformation._averageFuelConsumptionTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new RealEncoder(getEncodable().getFuelConsumption(), TripEndTypeInformation._fuelConsumptionTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getCo2(), TripEndTypeInformation._co2TypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getIdleTime(), TripEndTypeInformation._idleTimeTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new IntegerEncoder(getEncodable().getOdometer(), TripEndTypeInformation._odometerTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new CustomerEncoder(getEncodable().getCustomer(), TripEndTypeInformation._customerTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new PrintableStringEncoder(getEncodable().getEnterpriseName(), TripEndTypeInformation._enterpriseNameTypeInformation.getTypeInformation())
);
		componentEncoderList.add(
new SetOfEncoder<Driver>(
new DriverEncoder(null, TripEndTypeInformation._driverTypeInformation.__driverTypeInformation.getTypeInformation())
, encodablesList2, TripEndTypeInformation._driverTypeInformation.getTypeInformation())
);

		encoder.encodeAsSet(componentEncoderList, getTypeInformation());
	}
}
